# Generated by Django 6.0 on 2025-12-08 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('openai_link', models.URLField(blank=True, null=True)),
                ('api_token', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('all', 'All')], default='all', max_length=10)),
                ('prompt', models.TextField()),
                ('tests', models.TextField(help_text='Python code that will be used as tests')),
            ],
        ),
        migrations.CreateModel(
            name='LLMResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField(help_text='Percentage 0..100')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('all', 'All')], default='all', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('llm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.llm')),
            ],
        ),
        migrations.CreateModel(
            name='LLMUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=512)),
                ('llm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.llm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('llm', 'user')},
            },
        ),
    ]
